name: CI

on:
  push:
    branches: [ 'main', 'dev' ]
  pull_request:

jobs:
  lint_and_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Run pre-commit hooks for all files
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3
        with:
          extra_args: '--all-files'
